-- SkillTrace Phase 2: persistent candidate registry + audit trail
create table if not exists public.candidates (
  id text primary key,
  name text not null,
  district text,
  training text not null,
  skills text[] not null default '{}',
  status text not null default 'Seeking',
  employer text,
  role text,
  salary integer not null default 0,
  joined date,
  verified boolean not null default false,
  retention text,
  education text,
  experience integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists candidates_district_idx on public.candidates(district);
create index if not exists candidates_status_idx on public.candidates(status);
create index if not exists candidates_training_idx on public.candidates(training);
create index if not exists candidates_created_at_idx on public.candidates(created_at desc);
alter table public.candidates enable row level security;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_email text not null,
  role text not null default 'admin',
  event text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_idx on public.audit_logs(actor_email);
alter table public.audit_logs enable row level security;

-- The service-role key is used only by Vercel server functions.
-- Never expose it in React, browser code, or GitHub.
